### ISSUE TITLE
[ISSUE] HW4 올려주세요.

### ISSUE THREAD

**Issue by hyunsung-kim** [gpwls320/homework#1]
@gpwls320  과제 올려주시고 아래에 댓글 달아주시면 확인하겠습니다. 👍

**Comment by gpwls320** [comment]
코드는 대충 짰는데 homework4.py파일 14라인에서 에러가 나서 확인을 못하고 있어요ㅠㅠ 
뭐가 문제인걸까요ㅠㅠ.. 흑

**Comment by gpwls320** [comment]
fix_2020.04.05 로 올렸습니다 :)
